INSTDIR:=/usr/local/include/pfq/
all:
clean:
install:
		mkdir -p ${INSTDIR}
		cp pfq.hpp ${INSTDIR}
		cp pfq-except.hpp ${INSTDIR}
		cp pfq-queue.hpp ${INSTDIR}
		cp pfq-util.hpp ${INSTDIR}
		cp pfq-lang.hpp ${INSTDIR}
		cp pfq-default.hpp ${INSTDIR}
