INSTDIR:=/usr/local/include/pfq/
all:
clean:
install:
		mkdir -p ${INSTDIR}
		mkdir -p ${INSTDIR}/pfq-lang
		cp pfq.hpp ${INSTDIR}
		cp pfq-except.hpp ${INSTDIR}
		cp pfq-queue.hpp ${INSTDIR}
		cp pfq-util.hpp ${INSTDIR}
		cp pfq-lang/lang.hpp ${INSTDIR}/pfq-lang
		cp pfq-lang/default.hpp ${INSTDIR}/pfq-lang
		cp pfq-lang/details.hpp ${INSTDIR}/pfq-lang
