# SCon script

env = Environment(CPPPATH=['.',  '../C++', '../C', '../utils', '../../kernel'], 

CXXFLAGS=['-Ofast','-march=native', '-Wall', '-Wextra', '-std=c++11'])

env.Program(target = "pfq-counters",  source = ["pfq-counters.cpp"],  LIBS = ['pthread'])
env.Program(target = "pfq-histogram", source = ["pfq-histogram.cpp"], LIBS = ['pthread'])

