# SCon script

env = Environment(CPPPATH=['.',  '../C++', '../C', '../../kernel'], 
    CXXFLAGS=['-Ofast','-g2', '-Wall', '-Wextra', '-std=c++11'])
 
env.Append(LIBPATH='../C')

env.Program(target = 'pcap-test-rewrite', source = ['pcap-test-rewrite.cpp'], LIBS=['pcap'])
env.Program(target = "test-regression",   source = ["test-regression.cpp"], LIBS = ['pthread'])
env.Program(target = "test-regression-capture",   source = ["test-regression-capture.cpp"], LIBS = ['pthread', 'pcap'])
env.Program(target = "test-regression-c", source = ["test-regression-c.c"], LIBS = ['pthread', 'pfq'])

