INSTDIR:=/usr/local/include/pfq
all:
clean:
install:
		mkdir -p ${INSTDIR}
		mkdir -p ${INSTDIR}/lang
		cp pfq.hpp ${INSTDIR}
		cp exception.hpp ${INSTDIR}
		cp queue.hpp ${INSTDIR}
		cp util.hpp ${INSTDIR}
		cp lang/lang.hpp ${INSTDIR}/lang
		cp lang/default.hpp ${INSTDIR}/lang
		cp lang/details.hpp ${INSTDIR}/lang
