# SCon script

env = Environment(CPPPATH=['.',  '../C++', '../C', '../../kernel'], 

CFLAGS=['-O3','-march=native', '-Wall', '-Wextra' ])

env.Append(CPPDEFINES=['_GNU_SOURCE'])

env.Library(target = 'pfq', source = ['libpfq.c'])


